export type CsvRow = {
  ies: string;
  idIes: string;
  clientId: string;
  cpf: string;
  name: string;
  installmentId: string;
  principiaInstallmentId: string;
  settlementId: string;
  paymentId: string;
  product: string;
  idealCollector: string;
  realCollector: string;
  settlementType: string;
  paymentMethod: string;
  dueDate: string;
  settlementDate: string;
  paymentDate: string;
  principalAmount: string;
  chargeAmount: string;
  interestAmount: string;
  fineAmount: string;
  discountAmount: string;
  receivedAmount: string;
  paymentPercentage: string;
  externalPaymentId: string | null;
  settlementStatus: string;
  feePercentage: string;
  feeValue: string;
  lastUpdate: string;
  createdAt: string;
  updatedAt: string;
  GuaranteedIncomePaymentsViewFeeId: string;
};
